# Generated by Django 5.1 on 2024-08-15 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='last_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
